---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: __NAMESPACE__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb:11
          env:
            - name: MYSQL_DATABASE
              value: __NAMESPACE__
            - name: MYSQL_USER
              value: __NAMESPACE__
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: __NAMESPACE__-secrets
                  key: mysql-root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: __NAMESPACE__-secrets
                  key: mysql-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
...
